### PR TITLE
feat: add recommndations widget

### PR DESCRIPTION
**Pull request by danielkryska**
### Issue #67 

- Add a top bar into recommendation widgets to change recommendations types
image

- Extend recommendations types (the same as in Search Service & in the same order)
- Add all recommendations types tab
- Add the possibility to suit the best user recommendations in case of external recommendations failure

### CODE REVIEW

**Review by tomaszandel — APPROVED** [review]

**Comment by Marcelinna** [comment]
html marks are visible 
image

**Comment by Marcelinna** [comment]
lack of Horizontal Services, Stories, News tab
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
I can't click in the recomendation name
image

**Comment by Marcelinna** [comment]
I click on Publisher name, keyword, author name on recommended publication but I am redirected to SS to All catalogs view
image

**Comment by danielkryska** [comment]
- https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400142812
not in the scope of the ticket
- https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400144241
not enough time to resolve the issue
- https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400154646
@jarekzet problem
- [ ] https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400156821
I'll fix the issue by the end of the day. The URLs will provide the specific platform with more details about an item.
- https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400163112
Redirection to all catalogs page is correct behavior.
- pagination is out of the scope

**Comment by Marcelinna** [comment]
When I click on the publisher on recomendation panel, I have no result in SS
image
image

**Comment by Marcelinna** [comment]
When I click on the licence on recomendation panel, I have no result in SS
image
https://search.eosc-portal.eu/search/all?q=*&fq=license:(%22CC%20BY%204.0%22)
image

**Comment by Marcelinna** [comment]
When I click e.g author on recommended,publication, in SS filter is in "()"
image

**Comment by agpul** [comment]
image
Why sometimes the field "Type" is visible more than once?

**Comment by Marcelinna** [comment]
lack of type
image

**Comment by danielkryska** [comment]
- Newses added
image

- URLs redirections added (fixed)
https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400156821

- this is the Search Service issue (bug)
https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400207488

Since we do not support filtration by provider field, we won't be able to search by the field inside of Search Service. 

- https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400275643
fixed

**Comment by danielkryska** [comment]
fixed
- https://github.com/cyfronet-fid/eosc-user-dashboard/pull/105#issuecomment-1400291236

image

**Comment by Marcelinna** [comment]
@danielkryska links to training doesnt work
image
image

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
