### PR TITLE
feat: evaluation panel aligned with recommender #116 #143 #161

### PR DESCRIPTION
**Pull request by tomaszandel**

### CODE REVIEW

**Comment by aleksandrahojszyk** [comment]
Please adjust to the new version of UI https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?type=design&node-id=679%3A25587&t=AxupFxJKMJFI2LoF-1

**Comment by tomaszandel** [comment]
> 

Unfortunately its not on our side. They should sent us updated list without those disliked items,so its ok., because thewy are n ot reacting to our dislikes, we are hidding it like that. We cannot even hide them for real, as you may get 0 results if we do

**Comment by tomaszandel** [comment]
> 

yes we can adjust this one, that is ok

**Comment by agpul** [comment]
Acceptance criteria:
- [ ] As a User I can see the information page with a link to the dashboard (if I have no fav)
- [ ] As a User I can dislike each type of product
- [ ] As a User I can send information about why I don't like each product ( after clicking dislike)
- [ ] As a User I can "undo" the action
- [ ] As a User I see "Disliked" banner (it will be visible until we receive the new record from RS)

**Comment by Marcelinna** [comment]
@tomaszandel add space
image

**Comment by tomaszandel** [comment]
> @tomaszandel
> 
> can you adapt it to the view in figma? button color and new line https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?type=design&node-id=1043-26008&t=hpskymE3Ea9h2CoM-0 image FIGMA image

done

**Review by Marcelinna — APPROVED** [review]

**Review by Michal-Kolomanski — APPROVED** [review]

**Pull request merged**
