### PR TITLE
2846 new entry page

### PR DESCRIPTION
**Pull request by jarekzet**
new layout of intro page
https://www.figma.com/proto/RHmHoBRvx1oon6JwKK3Iaf/EOSC-Dashboard?node-id=1946%3A5549&scaling=scale-down-width&page-id=1779%3A6576

### CODE REVIEW

**Comment by Marcelinna** [comment]
@danielkryska  I can't login in, please check it
image

**Comment by Marcelinna** [comment]
shoul be Softwares not Software
image

**Review by danielkryska — CHANGES_REQUESTED** [review]
- commits need to be rebased and combined
- better commit messages required

**Comment by Marcelinna** [comment]
@agpul @aleksandrahojszyk 
image
image

Please please check the text in figma

**Comment by Marcelinna** [comment]
text should be changed

figma
image

pr
image

**Comment by Marcelinna** [comment]
button should be on the same hight 
image

**Comment by Marcelinna** [comment]
master (https://eosc-user-dashboard.docker-fid.grid.cyf-kr.edu.pl/dashboard)
image

pr
image

**Comment by Marcelinna** [comment]
color

pr
image

figma
image

**Review by Marcelinna — APPROVED** [review]

**Review by danielkryska — APPROVED** [review]

**Pull request merged**
