### PR TITLE
New dashboard view

### PR DESCRIPTION
**Pull request by jarekzet**

### CODE REVIEW

**Comment by aleksandrahojszyk** [comment]
Screenshot 2023-02-28 at 12 09 01
mozemy tak zrobić żeby dojeżdżało to tylko do stopki i jej nie zasłaniało?

**Comment by Marcelinna** [comment]
@jarekzet link to communities is linked only to the image. Can you add link to the communities title too?
image

**Comment by Marcelinna** [comment]
@jarekzet Can you add 2 communities in one column? (as in Figma)
image

**Comment by Marcelinna** [comment]
@jarekzet Can we change the label color on the recommendation
image
https://www.figma.com/file/Xis7MP81TIpPj1MWgbebN9/Dashboard-2?node-id=0%3A1&t=3KD9X6xO4LUbV40H-0

**Comment by Marcelinna** [comment]
@jarekzet Can we move keyowrds above (to start on a new line)
image

**Review by tomaszandel — APPROVED** [review]

**Pull request merged**
